# AppVeyor Build Konfiguration
# https://www.appveyor.com/docs/build-configuration/

#### Define each build for the extension
environment:
  matrix:
    - image: Visual Studio 2017

before_build:
  - mkdir build

build_script:
  - cd build
  - cmake ..
  - msvc

after_build:
  - cd ..
  - 7z a %buildname%_%name%.zip build

matrix:
  fast_finish: true

artifacts:
  - path: '*.zip'
